### ISSUE TITLE
API Wrapper: Use Case API Initiative (Ongoing)

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ce#182]
# Epic

## Description

With our EDC API Wrapper and EDC API Clients underway the goal is to develop an API for Use Case Application developers that can contain a simplified EDC workflow, and more stable API endpoints than our UI endpoints. This is required because our API Wrapper UI API is both tightly coupled to the UI scope and subject to change over time depending on UI needs.

### Requirements

- [x] #187 

## Work Breakdown

- [ ] Implement simplified workflow
  - [ ] createDataOffer
  - [ ] updateDataOffer
  - [ ] negotiateContract
  - [ ] initiateTransfer
  - [ ] transfers
  - [x] catalog
- [ ] Decide which other Management API endpoints to wrap
  - [ ] Vault Access
  - [ ] getContracts
  - [ ] getAssets
  - [ ] getAssetById
  - [ ] getContractById
  - [ ] getTransferById
- [ ] #958

## Acceptance criteria and must have scope

- [ ] Simplified Workflow working.
- [ ] Transferring data is possible.

**Comment by timdahlmanns** [comment]
### Regarding the incorrectly generated model schemas in the OpenAPI specification:

The root caus of the problem is in the EDC Connector, as the specification is already not generated correctly there. 
The schemas in the [EDC management-api](https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.0.1-SNAPSHOT#/Constraint) for example are already wrong. 
_Constraint_ is not resolved further, so that different _Constraint_ types and _Expression_ schemas do not exist.

On this topic there is also already an issue in the EDC Connector: https://github.com/eclipse-edc/Connector/issues/1264 <br>
Starting from this issue there are multiple issues in the swagger-core (https://github.com/swagger-api/swagger-core/issues/4181, https://github.com/swagger-api/swagger-core/issues/280, https://github.com/swagger-api/swagger-core/issues/2863, https://github.com/swagger-api/swagger-core/issues/3411)
which I understand as not supporting Jackson annotations to correctly resolve polymorphism for the generation of OpenAPI specifications.

---

IMHO we now have 4 options:

1. Adding swagger annotation (e.g `@Schema`) to the policy-model of the EDC Connector.
    - (:+1:) Pro: Fixes the OpenAPI specification for both the Connector and the Wrapper.
    - (:-1:) Con: Adds a dependency to the policy-model module and it must also be accepted by the EDC people.
2. Extending the swagger core resolver (https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver) like mentioned in https://github.com/swagger-api/swagger-core/issues/3411. I didn't really understand where to overwrite the resolver, but it sounds like a possible solution.
    - (:+1:) Pro: Doesn't require adding a dependency to the swagger annotations, since the custom resolver could read `@JsonSubTypes` annotations.
    - (:-1:) Con: Still need to add annotation to the EDC policy-model that must be accepted by the EDC people.
3. (__Implemented__) Extending the Gradle resolve task to merge the generated YAML specification with another YAML file that contains the fixed and missing schmeas.
    <details>
    <summary>Details</summary>
    
    ### build.gradle.kts
    ```kts
    tasks.withType<io.swagger.v3.plugins.gradle.tasks.ResolveTask> {
        outputDir = file(openapiFileDir)
        outputFileName = openapiFileFilename.removeSuffix(".yaml")
        prettyPrint = true
        outputFormat = io.swagger.v3.plugins.gradle.tasks.ResolveTask.Format.YAML
        classpath = java.sourceSets["main"].runtimeClasspath
        buildClasspath = classpath
        resourcePackages = setOf("de.sovity.edc.ext.wrapper.api")

        /**
        * Replace incomplete and add missing model schemas
        * in the 'build/swagger/edc-api-wrapper.yaml' open API specification.
        * The schemas defined in the 'edc-schemas.yaml' file are used for this.
        */
        doLast {
            val objectMapper = ObjectMapper(YAMLFactory())
            val openApi = objectMapper.readTree(File(openapiFile)) as ObjectNode
            val model = objectMapper.readTree(File("${project.projectDir}/edc-schemas.yaml")) as ObjectNode
            val openApiSchemas = openApi.get("components").get("schemas") as ObjectNode
            for (schema in model.get("schemas").fields()) {
                if (openApiSchemas.has(schema.key)) {
                    openApiSchemas.replace(schema.key, schema.value)
                } else {
                    openApiSchemas.set(schema.key, schema.value)
                }
            }
            File(openapiFile).writeText(openApi.toPrettyString())
        }
    }
    ```

    ### edc-schemas.yaml
    ```yaml
    schemas:
      AndConstraint:
        type: object
        properties:
          constraints:
            type: array
            items:
              $ref: '#/components/schemas/Constraint'
      AtomicConstraint:
        type: object
        allOf:
          - $ref: '#/components/schemas/Constraint'
          - type: object
            properties:
              leftExpression:
                $ref: '#/components/schemas/Expression'
              rightExpression:
                $ref: '#/components/schemas/Expression'
              operator:
                type: string
                enum:
                  - EQ
                  - NEQ
                  - GT
                  - GEQ
                  - LT
                  - LEQ
                  - IN
      OrConstraint:
        type: object
        properties:
          constraints:
            type: array
            items:
              $ref: '#/components/schemas/Constraint'
      XoneConstraint:
        type: object
        properties:
          constraints:
            type: array
            items:
              $ref: '#/components/schemas/Constraint'
      Constraint:
        required:
          - edctype
        type: object
        properties:
          edctype:
            type: string
        description: constraint test
        discriminator:
          propertyName: edctype
        oneOf:
          - $ref: '#/components/schemas/AtomicConstraint'
          - $ref: '#/components/schemas/AndConstraint'
          - $ref: '#/components/schemas/OrConstraint'
          - $ref: '#/components/schemas/XoneConstraint'
      Expression:
        required:
          - edctype
        type: object
        properties:
          edctype:
            type: string
        description: expression test
        discriminator:
          propertyName: edctype
        oneOf:
          - $ref: '#/components/schemas/LiteralExpression'
      LiteralExpression:
        type: object
        properties:
          value:
            type: object
    ```
    </details>

    - (:+1:) Pro: No changes to the EDC Connector and the wrapper itself. Other possible errors of the generator could be solved by the second YAML file.
    - (:-1:) Con: YAML file must be kept up to date manually (but only a single file).
4. Copy all necessary model classes to the Wrapper and add swagger annotations.
    - (:+1:) Pro: No changes to the EDC Connector.
    - (:-1:) Con: Many model classes must be kept up to date manually (min. 20).
  
---  
  
Let me know if you have any corrections or other ideas.

**Comment by richardtreier** [comment]
> 4\. Copy all necessary model classes to the Wrapper and add swagger annotations.

To summarize from friday: This is what it will most likely be. We will decide the own data amount to return per endpoint which might be less than the Management API returns or more, making that the resulting objects don't have a 1-to-1 relation, maybe not even by structure.

We do not need to copy all the classes, but can decide on a per-endpoint basis what the right thing to return is.

For cases with polymorphisms, such as the EDC Expression class we need to provide sum types, so we A) have a decided and clear cut scope we support and B) they can work in the generated clients, as overriding JSON in Java is not easy.

**Comment by richardtreier** [comment]
> As I understand from the current status of the API Wrapper, we have implemented simplified workflow already. Assuming my understanding is correct, we should evaluate what remains to be completed and define the solution proposal accordingly.
> 
> Target for evaluation is: Sprint 43

No we have not. The idea is to offer a simplified "createDataOffer", "deleteDataOffer", "listDataOffers" as single API calls

**Comment by SebastianOpriel** [comment]
@richardtreier what is the status?
