### ISSUE TITLE
[Broker] v2.0.0 - Product Increment 1

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ce#935]
# General
## Goal

New Functionality beyond the MvP 0.1.0 functionality.

## Breakdown
- Roles and Rights-Managmeent
  - [ ] sovity/edc-extensions#946
  - [ ] sovity/edc-extensions#947
- Broker Management Features
  - [ ] sovity/edc-extensions#937 
  - [x] sovity/edc-broker-server-extension#138
  - [ ] sovity/edc-extensions#949
- Reports
  - [ ] sovity/edc-extensions#945
- Transparency Features
  - [x] https://github.com/sovity/edc-broker-server-extension/issues/55
  - [x] https://github.com/sovity/edc-broker-server-extension/issues/109
  - [x] https://github.com/sovity/edc-broker-server-extension/issues/52
  - [x] https://github.com/sovity/edc-broker-server-extension/issues/56
- MDS EDC Connector
  - [x] sovity/edc-extensions#941 
  - [x] sovity/edc-broker-server-extension#131 
  - [ ] https://github.com/sovity/edc-extensions/issues/939
- Release
  - [ ] https://github.com/sovity/edc-extensions/issues/943
  - [ ] sovity/edc-extensions#938 

# Stakeholders
@alexanderaukam @sebk46
