### ISSUE TITLE
Markdown support for fields `Reference files description` and `Conditions for use`

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ce#989]
Adjust fields:
-  Reference files description
- Conditions for use
to be processed as Markdown.

## Tasks

- [ ] Adjust displaying field content as markdown in views in EDC UI
- [ ] Adjust displaying field content as markdown in views in Broker (i.e. Authority Portal)
- [ ] Adjust field info on creation: Add hint about markdown support
- [ ] If necessary adjust field info on edit page.
